# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm7_arm_controller
    - xarm7_hand_controller

  xarm7_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    action_ns: follow_joint_trajectory
    default: true
  xarm7_hand_controller:
    type: GripperCommand
    joints:
      - drive_joint
    action_ns: gripper_cmd
    default: true