sensors:
  - default_sensor
default_sensor:
  far_clipping_plane_distance: 2.0
  filtered_cloud_topic: iltered_cloud_from_depthmap
  image_topic: /camera/camera/depth/image_rect_raw
  max_update_rate: 10.0
  near_clipping_plane_distance: 0.1
  padding_offset: 0.01
  padding_scale: 1.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.05